version: '3.8'

services:
    dev:
        container_name: git_and_job_backend_dev
        image: git-and-job-backend-dev:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: npm run start:debug
        ports:
            - 3000:3000
            - 9229:9229
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
    db:
      image: postgres
      environment:
       - POSTGRES_DATABASE: "${DB_DATABASE}"
       - POSTGRES_USER: "${DB_USER}"
       - POSTGRES_PASSWORD: "${DB_PASSWORD}"
    prod:
        container_name: git_and_job_backend_prod
        image: git-and-job-backend-prod:1.0.0
        build:
            context: .
            target: production
            dockerfile: ./Dockerfile
        command: npm run start:prod
        ports:
            - 3000:3000
            - 9229:9229
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped

networks:
    nesjs-network: